services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3333:3333'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}